export default {
  dashboard: "대시보드",
  my_dashboard: "나의 대시보드",
  balance: "균형",
  connect_wallet: "커넥트 월렛",
  learn_more: "더 알아보기",
  wallet: "지갑",
  max: "최대치",
  min_amount: "Min 금액",
  you_will_need_bnb_in_your_wallet: "당신의 월렛 안에 BNB를 보유하고 계셔야 합니다.",
  usd: "USD",
  apy: "APY",
  total_staked: "총 스테이킹된 양",
  daily_rewards: "일일 보상",
  weekly_rewards: "주별 보상",
  pool_statistics: "풀 통계",
  monthly_rewards: "월별 보상",
  my_deposit: "내 예치금",
  share_of_pool: "풀 공유",
  my_vaults: "내 금고",
  exchange: "거래",
  staked_amount: "스테이킹된 양",
  claimed_amount: "청구 금액",
  total_growth: "총 성장",
  total_stakers: "총 스테이커",
  deposit: "예치금",
  team: "팀",
  referral_link: "관련링크",
  current_rank: "현재 랭크",
  partners: "파트너",
  level_name: "레벨 이름",
  own_active_gymnet_farm: "자체 활성 GYMNET 농장",
  to_reach_next_rank: "다름 랭크에 도달하기",
  direct: "직접",
  own_deposit: "고유 예치금",
  gained: "획득한",
  rank: "랭크",
  reward: "보상",
  all: "전부",
  my: "나의",
  required_partners: "요구된 파트너",
  statistic_rewards: "통계 보상",
  own_single_pool_needed: "필요한 자체 싱글풀",
  unlocked_ranks: "잠금 해제된 랭크",
  invested: "투자된",
  connect_to_wallet: "지갑 연결하기",
  choose_wallet: "지갑 선택하기",
  i_read_and_accept: "읽었으며 동의함",
  company_icon: "회사 아이콘",
  total_vaults_deposit: "총 금고 예치금액",
  total_income: "총 수입",
  gymnet_earned: "벌어들인 GYMNET",
  investment: "투자",
  your_address: "당신의 주소",
  manage_wallets: "지갑 관리하기",
  wallet_icon: "지갑 아이콘",
  copy_icon: "복사 아이콘",
  history: "방문 기록",
  time_icon: "시간 아이콘",
  view_on_bscScan: "Bscscan 보기",
  redirect_icon: "리디렉트 아이콘",
  the_referral_system_and_the_profit_commissions: "추천 시스템에는 25개의 레벨이 있으며 레벨당 수익 수수료는 다음과 같이 표시됩니다.",
  the_referral_system_and_the_profit_commissions_description1: "레벨 14, 15 또는 16에 대한 자격이 되면 글로벌 풀 셰어에도 참여하게 됩니다. 이 경우 자신의 팀 구성에 관계없이 GYM NETWORK 전체에서 생성된 전체 이익과 보상의 일부를 받게 됩니다. 예를 들어 레벨 16이면 플래티넘 풀 자격이 됩니다. 이 경우 제휴 시스템에 분배되는 GYM NETWORK 전체 이익 및 보상의 1.5%를 귀하의 몫으로 받게 됩니다.",
  the_referral_system_and_the_profit_commissions_description2: "후원하는 파트너가 GYM NETWORK 내에서 활성 상태를 유지하는 한 실제로 좋은 수동 소득원과 동일한 수수료를 받고 있습니다. 다른 사람들이 DeFi로 수익을 낼 수 있도록 돕고 이를 통해 수동 소득을 얻으세요.",
  turnover_pool_monthly: "월별 풀 턴오버",
  level_pool_daily: "일일 레벨 풀",
  regional: "지역적",
  national: "국가적",
  international: "국제의",
  gold: "금",
  level: "레벨",
  platin: "백금",
  black: "블랙",
  vault: "금고",
  strategy: "전략",
  vaults: "금고",
  tokens: "토큰",
  gymnet_icon: "GYMNET 아이콘",
  total_gymnet_vaults_rewards: "총 GYMNET 금고 보상",
  claim_all: "모두 청구하기",
  all_vaults: "모든 금고",
  coming_soon: "곧 출시",
  rewards: "보상",
  claim: "청구하기",
  vaultCommissions: "금고 커미션",
  farmingCommissions: "파밍 커미션",
  singlePoolCommissions: "싱글풀 커미션",
  vaultCommissionsTotal: "총 금고 커미션",
  totalInvestorsProfit: "총 투자자 소득",
  pendingCommissions: "팬딩 커미션",
  commissionsFromVaultInvestors: "금고 투자자로부터의 커미션",
  partnerActivity: "파트너 활동",
  date: "날짜",
  user: "사용자",
  amount: "금액",
  token: "토큰",
  tx: "TX",
  loadMore: "더 불러오기",
  dailyROI: "일일 ROI",
  hourlyROI: "시간당 ROI",
  totalLiquidity: "총 유동성",
  totalTokensLocked: "총 잠긴 토큰",
  viewContract: "계약서 보기",
  seePairInfo: "페어 정보 보기",
  myStake: "나의 스테이킹",
  myStakeText: "여기서 더 많은 보상을 얻기 위한 당신의 짐 토큰 예치를 할 수 있습니다.",
  addLiquidityStake: "유동성 및 스테이킹 더하기",
  gymnetEarned: "벌어들인 GYMNET",
  claimStake: "청구 및 스테이킹하기",
  addLiquidutyStake: "유동성 및 스테이킹 더하기",
  gymnetAndBnb: "gymnet 및 bnb",
  gymnetAndBusd: "gymnet 및 busd",
  gymnet: "gymnet",
  bnb: "bnb",
  withdraw: "인출하기",
  balanceNum: "균형",
  claim_and_farm: "청구 및 파밍",
  compound_your_gymnet: "당신의 GYMNET을 연결하세요",
  claimAndFarm: "청구 및 파밍",
  your_total_deposit: "당신의 총 예치금액",
  total_pending_rewards: "총 펜딩 보상",
  total_own_claimed: "총 청구금액",
  active_holdings: "홀딩 활성화시키기",
  archived_holdings: "홀딩 보관",
  with_locking_period: "잠금 기간 설정하기",
  without_locking_period: "잠금 기간 없이",
  deposit_amount: "금액 예치하기",
  pending_rewards: "펜딩보상",
  you_dont_receive_pending_rewards_for_deposit_without_locking_period: "잠금기간 설정없이 한 예치금에 대한 보상은 받으실 수 없습니다.",
  lpTokensWillBeAutomaticallyStakedOnTheFaringContract: "LP토큰은 자동적으로 운임 계약 아래 스테이킹 됩니다.",
  depositFeeForBuyAndBurn: "구매 및 소각시스템에 따른 4%의 예치 수수료",
  unlock: "잠금해제",
  halfOfYourGymNetTokensWillBeUsed: "당신의 GYMNET 토큰의 절반은 BNB의 구매를 위해 사용되며 따라서 그것은 풀링되고 스테이킹 계약에 의해 스테이킹될 것입니다.",
  halfOfYourBnbTokensWillBeUsed: "당신의 BNB의 절반은 GMYNET 토큰의 구매를 위해 사용되며 그럼 그것은 풀링되고 스테이킹 계약에 의해 스테이킹될 것입니다.",
  removeLiquidity: "유동성 제거하기",
  pooled: "풀링",
  unstake: "언스테이킹",
  lpTokensWillBeInYourWallet: "당신의 지갑 속에 LP토큰이 있을 것입니다. 이 작업이 마친 뒤에 BNB와 GYMNET토큰을 얻기 위해서는 '유동성 제거하기' 버튼을 클릭해주세요.",
  dailyProfit: "일일 소득",
  withdraw_and_claim: "인출 및 청구하기",
  pending_GYMNET_reward: "GYMNET 보상 펜딩하기",
  LP_tokens_will_be_in_your_wallet: "당신의 지갑 안에 LP토큰이 있을 것입니다. BNB 및 GYMNET토큰을 얻기 위해서는 이 동작이 완료된 뒤에 '유동성 제거하기' 버튼을 클릭해 주세요.",
  claim_and_deposit_to_sp: "청구 및 싱글풀에 예치하기",
  claim_and_deposit: "청구 및 예치하기",
  deposit_with_locking_period: "잠금 기간과 같이 예치하기",
  claimAndDeposit: "청구 및 예치하기",
  depositWithLockingPeriod: "잠금 기간과 같이 예치하기",
  confirmLockingPeriod: "잠금기간 확인하기",
  total_gymnet_locked_in_pool: "총 풀에 잠긴 GYMNET",
  total_claimed: "총 청구된 금액",
  reward_per_block: "블록 별 보상",
  start_date: "날짜 시작하기",
  end_date: "날짜 끝내기",
  launch_of: "출시",
  locked: "잠긴",
  months: "월",
  nothing_to_show: "볼 것이 없음",
  you_will_receive_commissions_text: "당신의 다운라인에서 커미션을 받을 것입니다. 그리고 랭킹상태에 따라서 자격을 부여받을 것입니다.",
  deposit_fee_for_burn: "소각을 위한 예치 수수료",
  no_data_found: "데이터를 찾을 수 없음",
  disconnect_wallet: "지갑 연결 해제하기",
  confirm_trans: "거래 확인하기",
  confirm: "팝업창에서 거래를 확인해주세요",
  okay: "알겠음",
  waiting_trans: "거래확인을 기다리는 중",
  wait: "잠시만 기다려 주십시오.",
  confirmed: "거래확인되었음",
  products: "상품",
  eco_system: "생태계",
  about: "관하여",
  blog: "블로그",
  launch_to_app: "APP 시작하기",
  header_title: "당신의 토큰을 위한 완벽한 워크아웃",
  header_description: "우리는 당신께서 최고의 디파이 리턴즈에 접근하실 수 있도록 해드립니다. 어려운 작업을 우리의 일이며 당신께서는 단지 결과를 보상으로 받으시면 됩니다.",
  total_burnt: "총 소갹량",
  gymnet_price: "GYMNET 가격",
  total_supply: "총 공급량",
  total_value_locked: "총 잠긴가치",
  listed_on: "GYMNET은 리스트되어 있습니다.",
  listed_on_title: "GYMNET은 리스트되어 있습니다.",
  investment_system_title: "GYM NETWORK - 디파이 애그리게이터 투자시스템",
  investment_system_description: "Gym Network는 최상의 수익률을 사용자에게 높은 보상과 결합하는 Defi Aggregator Investment 시스템입니다. 따라서 쉽게 접근 할 수 있고 소중한 시간을 많이 절약 할 수 있습니다. 지갑으로 직접 결함 공간에서 최고의 수확량을 얻는다고 상상해보십시오. 이제 당신의 꿈이 현실이되게 할 때가 왔습니다!",
  go_to_the_products: "상품 보기",
  gymstreet_title: "GYM Street - 메타버스",
  gymstreet_description: "무엇이든 할 수 있는 곳! 일상의 미래로 GYM Street를 만듭니다. 일, 금융, 쇼핑, 커뮤니케이션, 부동산, 메타버스에서 새로운 삶을 요약하세요. GYM Street와 함께 Metaverse에서 상상하지 못한 잠재력을 발견하고 새로운 삶을 설계하십시오.",
  go_to_gymstreet: "GYM Street 입장하기",
  metaverse_desc: "“우리는 모든 사람이 디지털 미래의 일부이며 투자자로서 자신의 재정적 자유를 형성할 수 있는 세상을 보고 있습니다. Blockchain, DeFi 및 Metaverse에 대한 열정으로 우리는 내일의 솔루션을 만들고 있습니다.",
  protection_tools: "보호도구",
  price_stabilizer: "가격 안정화",
  stabilizer_desc: "금고로부터의 소득의 10%는 바이백 및 소각프로그램을 위해 사용됩니다.",
  gym_network_title: "GYM NETWORK와 함께 시작하는 방법",
  watch_tutorial: "튜토리얼 보기",
  affiliate_system_title: "GYM NETWORK 제휴시스템",
  affiliate_system_info: "GYM Network\'의 제휴 시스템으로 나만의 암호화폐 추천 사업과 장기 수동 소득을 구축할 수 있습니다.",
  affiliate_desc: "오늘 GYM 네트워크 커뮤니티의 일원이 되어 자신만의 재정적 자유를 만드십시오.",
  read_more: "더 읽기",
  roadmap_title: "GYM Network 로드맵",
  roadmap_desc: "미래에 대한 우리의 비전과 우리가 지금까지 구현한 것",
  faq: "자주 받는 질문들",
  join_telegram_group: "우리의 텔레그램 그룹방에 입장해주세요",
  join_telegram_group_desc: "GYM 네트워크에 대한 모든 최신 뉴스와 질문에 대한 답변을 얻으십시오!",
  join_now: "지금 가입하세요",
  footer_info: "메타버스와 DeFi Aggregator 투자 시스템의 결합. DeFi, Yield Farming, Staking, NFT 등에서 수익성 있는 수익을 창출합니다.",
  affiliate_system: "제휴 시스템",
  gym_network: "Gym Network",
  privacy_policy: "개인정보 보호정책",
  whitepaper: "백지",
  trans_success: "거래가 성공적으로 승인되었습니다.",
  unlock_and_stake: "잠금해제 및 스테이킹",
  deposit_to_sp: "싱글 풀에 예치하기",
  failed: "거래승인 실패",
  unlock_staking: "스테이킹 잠금해제하기",
  no_deposit_fee_for_burn: "소각을 위한 예치수수료는 없습니다.",
  no_apy: "APY는 없습니다.",
  unlocked: "잠금해제됨",
  terms_conditions: "기간 및 조건",
  enter_your_email: "당신의 이메일을 입력하십시오",
  verify_email: "이메일 인증하기",
  heading: "표제",
  your_sponsor_id: "당신의 스폰서 ID",
  terms_condition_accept_info: "이용약관에 동의한 후에는 추후 변경이 불가능하며, 자동으로 시행됩니다.",
  accept_terms_conditions: "기간 및 조건 동의하기",
  email: "이메일",
  confirm_your_email: "이메일을 확인하십시오",
  create_account: "계정을 생성하십시오",
  email_verification: "이메일 인증 코드가 발송되었습니다.",
  change_email: "이메일 변경하기",
  resend_code: "코드 재발송하기",
  turnovers: "턴오버",
  qualified_level_vault: "자격을 갖출 레벨 금고",
  unlimited_depth_vault: "무제한 깊이 금고",
  qualified_level_farm: "자격을 갖춘 레벨 팜",
  unlimited_depth_farm: "무제한 깊이 팜",
  qualified_depth_single_pool: "자격을 갖춘 깊이 싱글풀",
  unlimited_depth_single_pool: "무제한 깊이 싱글풀",
  deposit_partners_list: "직접 파트너 리스트",
  own_vault_deposit: "자체 금고 예치금",
  level_rank: "레벨 / 랭크",
  total_deposit_vault: "총 금고 예치금",
  total_liquidity_mining: "총 유동성 채굴량",
  total_single_pool: "총 싱글풀",
  total_partners: "총 파트너수",
  total_pool_rewards: "총 풀 보상",
  total_participants: "총 참여자수",
  unclaimed_gymnet_rewards: "청구되지 않은 GYMNET 보상",
  level_pool: "레벨 풀",
  vaults_contribution: "금고 기여도",
  single_contribution: "싱글 기여도",
  farming_contribution: "파밍 기여도",
  current_pending_rewards: "현재 펜딩 보상",
  participants: "참여자들",
  unclaimed_rewards: "청구되지 않은 보상",
  type: "유형",
  txId: "TxID",
  amount_before: "이전 금액",
  amount_after: "이후 금액",
  next_distribution: "다음 배포",
  ROI_at_current_stake: "현재 스테이킹된 ROI",
  received_gGymnet: "받은 GYMNET",
  about_voting_rights: "투표권에 대하여",
  you_successfully_verified_your_email: "이메일 인증이 성공적으로 완료되었습니다.",
  to_dashboard: "대시보드로",
  you_will_receive_your_tokens_text: "Wrapped BNB로 토큰을 받게 됩니다. WBNB를 지갑으로 가져와서 자금을 확인하십시오.",
  you_will_receive_your_tokens_text_BUSD: "BUSD로 토큰을 받게 됩니다. BUSD를 지갑으로 가져와 자금을 확인하십시오.",
  share_of_NFT_pool: "NFT 풀의 공유",
  partner_area: "파트너 지역",
  rockstar_rank_text: "록스타는 추가 자격 옵션으로 모든 사람이 더 쉬운 방법으로 3가지 다른 등급에 자격을 부여할 수 있습니다.",
  rockstar_ranks: "록스타 랭크",
  to_reach_rank_you_need: "(...)랭크에 도달하기 위해 당신이 필요한 것",
  all_ranks: "모든 랭킹들",
  reach_levels_much_easier: "레벨 10,23,24에 보다 더 쉽게 도달하세요",
  reach_levels_much_easier_text: "지금 4%의 구매 및 소각 수수료를 지불하고 새로운 조건에서 미래의 수준에 도달할 수 있습니다. 오퍼는 확인 T&C 확인 후 30일 동안 유효합니다.",
  rockstar_10_rank: "록스타 레벨 10",
  rockstar_10_rank_text: "모든 예금에 22000 USD 대신 7500 USD만 있으면 됩니다. 또한 9 등급에 대해 더 적은 보증금이 필요합니다. 자격을 갖춘 파트너 요구 사항이 없습니다.",
  single_pool_deposit: "싱글풀 예치금",
  vault_deposit: "금고 예치금",
  farming_deposit: "파밍 예치금",
  next: "다음",
  sponsor_id: "스폰서 아이디",
  back: "뒤로가기",
  ggymnet_amt: "Gymnet 금액",
  skip_guide: "가이드 건너뛰기",
  total_amount: "총 금액",
  rockstar10_23_24_ranks: "록스타 랭킹 10, 23, 24",
  rockstar_24_rank: "록스타 랭킹 24",
  rockstar_24_rank_text: "모든 예금에 135000 USD 대신 100000 USD만 있으면 됩니다. 자격을 갖춘 파트너 요구 사항이 없습니다.",
  rockstar_23_rank: "록스타 랭킹 23",
  rockstar_23_rank_text: "모든 예금에 120000 USD 대신 90000 USD만 있으면 됩니다. 또한 21, 22 등급의 경우 더 적은 보증금이 필요합니다. 자격을 갖춘 파트너 요구 사항이 없습니다.",
  swap: "교환하기",
  member: "회원",
  buy: "구매",
  choose_crypto_wallet: "암호화폐 지갑 선택",
  choose_crypto_wallet_desc: "MetaMast 혹은 Trus Wallet 같은",
  transfer_bnb: "BNB 교환",
  transfer_bnb_desc: "당신의 지갑으로",
  connect_your_wallet: "당신의 지갑을 연결하세요",
  connect_your_wallet_desc: "웹사이트로 이동하여 Vault에 첫 입금(0.051BNB부터)",
  ar_app_desc: "증강현실과 블록체인이 만나다! 운동 완료에 대한 보상을 받으면서 가상 체육관에서 훈련하세요",
  ar_app: "AR APP",
  ntf_marketplace_desc: "NFT 시장인 zuckerland.io에서 가치 있는 NFT를 투자, 수집 및 거래하세요.",
  ntf_marketplace: "NFT 시장",
  play_earn_desc: "완전히 독특한 DeFi 기반 복권인 무손실 복권과 같은 온라인 게임을 플레이하고 보상을 받으세요",
  play_earn: "게임하면서 돈벌기",
  launchpad_desc: "새로운 프로젝트가 시장에 출시되기 전에 가장 먼저 접근할 수 있습니다",
  launchpad: "런치패드",
  earn_crypto_desc: "Bitcoin, ETH, BNB, DOGE, Stablecoins 등에서 매력적인 수익을 얻으십시오.",
  earn_crypto: "암호화폐 벌기",
  gymnet_vault_desc: "가장 인기 있는 암호화폐 자산에 대한 최고의 관심을 받고 독특한 토큰 보상을 받으세요",
  gymnet_vault: "Gymnet 금고",
  metaverse: "메타버스",
  metaverse_slide_desc: "토지를 구입하여 미래의 모든 제품에 독점적으로 액세스하고 가상 세계에서 사용하세요",
  yield_farming_desc: "DeFi에서 가장 수익성이 좋은 파밍 거래 찾기",
  yield_farming: "양산 파밍",
  farming: "파밍",
  farm_sp: "팜 및 싱글 풀의 4%",
  farm_sp_desc: "예금은 인플레이션에 대응하기 위한 바이백 및 소각 프로그램에 사용됩니다.",
  locking_sp: "단일 풀에 락인",
  locking_sp_desc: "유통되는 GYMNET을 줄여 장기적으로 가격을 안정시키는 데 도움이 됩니다.",
  burning_gymnet: "GYMNET 소각",
  burning_gymnet_desc: "바이백 및 소각을 통해 GYMNET 가격이 상승하고 토큰 판매가 감소합니다.",
  through_codetermination_rights: "공동결정권을 통해",
  through_codetermination_rights_desc: "커뮤니티는 GYM 네트워크의 미래에 직접적인 영향을 미칩니다. ",
  single_pool: "싱글풀",
  buy_GYMNET: "GYMNET 구매하기",
  gymstreet: "GYMstreet",
  metablocks: "메타블럭",
  cashFT: "CashFT",
  zuckerland: "Zuckerland",
  metaverse_campus: "메타버스 캠퍼스",
  blog_news: "블록 및 뉴스",
  support: "서포트",
  newsletter: "뉴스레터",
  documentation: "Documentation",
  smart_contract: "스마트 계약",
  community: "커뮤니티",
  guide: "가이드",
  help: "도움",
  certik: "Certik으로부터의 감사",
  stability_program: "Gymnet 안정화 프로그램",
  audited: "감사",
  our_official_telegram: "우리의 공식 텔레그램",
  official_partner: "공식 파트너",
  // ....................

  tokenContract: "Token Contract",
  gymDex:"Gym Dex",
}
