export default {
  dashboard: "แดชบอร์ด",
  my_dashboard: "แดชบอร์ดของฉัน",
  balance: "ยอดคงเหลือ",
  connect_wallet: "เชื่อมต่อกระเป๋าเงิน",
  learn_more: "เรียนรู้เพิ่มเติม",
  wallet: "กระเป๋าเงิน",
  max: "สูงสุด",
  min_amount: "จำนวนเงินขั้นต่ำ",
  you_will_need_bnb_in_your_wallet: "คุณจะต้องมี BNB ในกระเป๋าเงินของคุณ",
  usd: "ดอลล่าร์",
  apy: "อัตราผลตอบแทนต่อปี",
  total_staked: "ยอดรวมวางเดิมพัน",
  daily_rewards: "รางวัลรายวัน",
  weekly_rewards: "รางวัลรายสัปดาห์",
  pool_statistics: "สถิติกองทุน",
  monthly_rewards: "รางวัลรายเดือน",
  my_deposit: "เงินฝากของฉัน",
  share_of_pool: "ส่วนแบ่งของกองทุน",
  my_vaults: "ห้องนิรภัยของฉัน",
  exchange: "แลกเปลี่ยน",
  staked_amount: "จำนวนเงินวางเดิมพัน",
  claimed_amount: "จำนวนเงินที่รับ",
  total_growth: "ยอดรวมการเติบโต",
  total_stakers: "ยอดรวมผู้วางเดิมพัน",
  deposit: "เงินฝาก",
  team: "ทีม",
  referral_link: "ลิงก์อ้างอิง",
  current_rank: "อันดับปัจจุบัน",
  partners: "พันธมิตร",
  level_name: "ชื่อระดับ",
  own_active_gymnet_farm: "ฟาร์ม GYMNET ที่ใช้งานอยู่",
  to_reach_next_rank: "เพื่อไปถึงอันดับถัดไป",
  direct: "โดยตรง",
  own_deposit: "เงินฝากของตัวเอง",
  gained: "รับแล้ว",
  rank: "อันดับ",
  reward: "รางวัล",
  all: "ทั้งหมด",
  my: "ของฉัน",
  required_partners: "พันธมิตรที่จำเป็น",
  statistic_rewards: "รางวัลสถิติ",
  own_single_pool_needed: "ต้องการกองทุนเดี่ยว",
  unlocked_ranks: "ปลดล็อกอันดับ",
  invested: "ลงทุนแล้ว",
  connect_to_wallet: "เชื่อมต่อกับกระเป๋าเงิน",
  choose_wallet: "เลือกกระเป๋าเงิน",
  i_read_and_accept: "ฉันอ่านและยอมรับ",
  accept_term_and_condition: "ยอมรับข้อกำหนดของ <span class='primary-color'>บริการ</span> และ <span class='primary-color'>นโยบายความเป็นส่วนตัว</span>",
  company_icon: "ไอคอนบริษัท",
  beidge_icon: "ไอคอน Beidge",
  total_vaults_deposit: "ยอดรวมเงินฝากห้องนิรภัย",
  total_income: "ยอดรวมรายได้",
  gymnet_earned: "GYMNET ที่ได้รับ",
  investment: "การลงทุน",
  your_address: "ที่อยู่ของคุณ",
  manage_wallets: "จัดการกระเป๋าเงิน",
  wallet_icon: "ไอคอนกระเป๋าเงิน",
  copy_icon: "ไอคอนคัดลอก",
  history: "ประวัติ",
  time_icon: "ไอคอนเวลา",
  view_on_bscScan: "ดูบน BscScan",
  redirect_icon: "ไอคอนเปลี่ยนเส้นทาง",
  the_referral_system_and_the_profit_commissions: "ระบบแนะนำมี 25 ระดับและค่าคอมมิชชั่นกำไรต่อระดับจะแสดงอยู่ด้านล่าง:",
  the_referral_system_and_the_profit_commissions_description1: "เมื่อคุณมีคุณสมบัติสำหรับระดับ 14 15 หรือ 16 คุณจะเข้าร่วมในหุ้นกองทุนโลกด้วย ในกรณีนี้ คุณจะได้รับส่วนแบ่งของผลกำไรและรางวัลโดยรวมที่สร้างขึ้นทั่วทั้ง GYM NETWORK โดยไม่คำนึงถึงโครงสร้างทีมของคุณเอง ตัวอย่างเช่น หากคุณอยู่ในระดับ 16 คุณมีสิทธิ์ได้รับกองทุนแพลตตินั่ม ในกรณีนี้ คุณจะได้รับส่วนแบ่ง 1.5% ของผลกำไรและรางวัลในวงกว้างของ GYM NETWORK ที่แจกจ่ายไปยังระบบพันธมิตร",
  the_referral_system_and_the_profit_commissions_description2: "ตราบใดที่พันธมิตรที่ได้รับการสนับสนุนของคุณยังคงใช้งานอยู่ใน GYM NETWORK คุณจะได้รับค่าคอมมิชชั่นซึ่งจริง ๆ แล้วเท่ากับกระแสรายได้แบบพาสซีฟ ช่วยให้ผู้อื่นทำกำไรด้วย DeFi และรับรายได้แบบพาสซีฟจากการทำเช่นนั้น",
  turnover_pool_monthly: "ผลประกอบการกองทุนรายเดือน",
  level_pool_daily: "กองทุนระดับรายวัน",
  regional: "ภูมิภาค",
  national: "ระดับชาติ",
  international: "ระหว่างประเทศ",
  gold: "ทอง",
  level: "ระดับ",
  platin: "แพลตตินั่ม",
  black: "สีดำ",
  vault: "ห้องนิรภัย",
  strategy: "กลยุทธ์",
  vaults: "ห้องนิรภัย",
  tokens: "โทเคน",
  gymnet_icon: "ไอคอน Gymnet ",
  total_gymnet_vaults_rewards: "ยอดรวมรางวัลห้องนิรภัย GYMNET",
  claim_all: "รับทั้งหมด",
  all_vaults: "ห้องนิรภัยทั้งหมด",
  coming_soon: "เร็ว ๆ นี้",
  rewards: "รางวัล",
  claim: "รับ",
  vaultCommissions: "ค่าคอมมิชชั่นห้องนิรภัย",
  farmingCommissions: "ค่าคอมมิชชั่นการทำฟาร์ม",
  singlePoolCommissions: "คอมมิชชั่นกองทุนเดี่ยว",
  vaultCommissionsTotal: "ค่าคอมมิชชั่นห้องนิรภัยทั้งหมด",
  totalInvestorsProfit: "ยอดรวมกำไรรวมของนักลงทุน",
  pendingCommissions: "ค่าคอมมิชชั่นที่รอดำเนินการ",
  commissionsFromVaultInvestors: "ค่าคอมมิชชั่นจากนักลงทุนในห้องนิรภัย",
  partnerActivity: "กิจกรรมพันธมิตร",
  date: "วันที่",
  user: "ผู้ใช้",
  amount: "จำนวน",
  token: "โทเคน",
  tx: "TX",
  loadMore: "โหลดเพิ่ม",
  dailyROI: "ผลตอบแทนจากการลงทุนรายวัน",
  hourlyROI: "ผลตอบแทนจากการลงทุนรายชั่วโมง",
  totalLiquidity: "ยอดรวมสภาพคล่อง",
  totalTokensLocked: "ยอดรวมโทเคนที่ถูกล็อก",
  viewContract: "ดูสัญญา",
  seePairInfo: "ดูข้อมูลคู่",
  myStake: "เงินเดิมพันของฉัน",
  myStakeText: "คุณสามารถฝากโทเคน GYM ของคุณเพื่อรับรางวัลเพิ่มเติมได้ที่นี่",
  addLiquidityStake: "เพิ่มสภาพคล่องและเงินเดิมพัน",
  gymnetEarned: "Gymnet ที่ได้รับ",
  claimStake: "รับและวางเดิมพัน",
  addLiquidutyStake: "เพิ่มสภาพคล่องและเงินเดิมพัน",
  gymnetAndBnb: "gymnet & bnb",
  gymnetAndBusd: "gymnet & busd",
  gymnet: "gymnet",
  bnb: "bnb",
  withdraw: "ถอน",
  balanceNum: "ยอดคงเหลือ: ß{n}",
  claim_and_farm: "รับและทำฟาร์ม",
  compound_your_gymnet: "รวบรวม GYMNET ของคุณ",
  claimAndFarm: "รับและทำฟาร์ม",
  your_total_deposit: "เงินฝากทั้งหมดของคุณ",
  total_pending_rewards: "ยอดรวมรางวัลที่รอดำเนินการ",
  total_own_claimed: "ยอดรวมที่รับเอง",
  active_holdings: "การถือครองที่ใช้งานอยู่",
  archived_holdings: "การถือครองที่เก็บถาวร",
  with_locking_period: "ด้วยระยะเวลาล็อก",
  without_locking_period: "ไม่มีระยะเวลาล็อก",
  deposit_amount: "จำนวนเงินฝาก",
  pending_rewards: "รางวัลที่รอดำเนินการ",
  you_dont_receive_pending_rewards_for_deposit_without_locking_period: "คุณไม่ได้รับรางวัลที่รอดำเนินการสำหรับการฝากเงินโดยไม่มีระยะเวลาล็อก",
  lpTokensWillBeAutomaticallyStakedOnTheFaringContract: "โทเคน LP จะถูกเดิมพันโดยอัตโนมัติในสัญญาทำฟาร์ม",
  depositFeeForBuyAndBurn: "ค่าธรรมเนียมการฝาก 4% สำหรับการซื้อและเผา",
  unlock: "ปลดล็อก",
  halfOfYourGymNetTokensWillBeUsed: "ครึ่งหนึ่งของโทเคน GYMNET ของคุณจะถูกใช้เพื่อซื้อ BNB จากนั้นจึงรวมและเดิมพันกับสัญญาวางเดิมพัน",
  halfOfYourBnbTokensWillBeUsed: "โทเคน BNB ของคุณครึ่งหนึ่งจะถูกใช้เพื่อซื้อ GYMNET จากนั้นจึงรวมและเดิมพันกับสัญญาวางเดิมพัน",
  removeLiquidity: "ลบสภาพคล่อง",
  pooled: "ลงกองทุน",
  unstake: "ยกเลิกวางเดิมพัน",
  lpTokensWillBeInYourWallet: "โทเคน LP จะอยู่ในกระเป๋าเงินของคุณ ในการรับโทเคน BNB และ GYMNET ให้คลิกปุ่ม “ลบสภาพคล่อง” หลังจากเสร็จสิ้นการดำเนินการนี้",
  dailyProfit: "กำไรรายวัน",
  withdraw_and_claim: "ถอนและรับ",
  pending_GYMNET_reward: "รางวัล GYMNET ที่รอดำเนินการ",
  LP_tokens_will_be_in_your_wallet: "โทเคน LP จะอยู่ในกระเป๋าเงินของคุณ ในการรับโทเคน BNB และ GYMNET ให้คลิกปุ่ม “ลบสภาพคล่อง” หลังจากเสร็จสิ้นการดำเนินการนี้",
  claim_and_deposit_to_sp: "รับและฝากไปยังกองทุนเดี่ยว",
  claim_and_deposit: "เรียกร้องและฝากเงิน",
  deposit_with_locking_period: "เงินฝากที่มีระยะเวลาล็อก",
  claimAndDeposit: "รับและฝากเงิน",
  depositWithLockingPeriod: "เงินฝากที่มีระยะเวลาล็อก",
  confirmLockingPeriod: "ยืนยันระยะเวลาการล็อก",
  total_gymnet_locked_in_pool: "ยอดรวม GYMNET ถูกล็อกในกองทุน",
  total_claimed: "ยอดรวมที่รับทั้งหมด",
  reward_per_block: "รางวัลต่อบล็อก",
  start_date: "วันที่เริ่มต้น",
  end_date: "วันที่สิ้นสุด",
  launch_of: "เปิดตัว",
  locked: "ล็อกแล้ว",
  months: "เดือน",
  nothing_to_show: "ไม่มีอะไรจะแสดง",
  you_will_receive_commissions_text: "คุณจะได้รับค่าคอมมิชชั่นจากดาวน์ไลน์ของคุณและจะมีคุณสมบัติตามเงื่อนไขอันดับ",
  deposit_fee_for_burn: "ค่าธรรมเนียมการฝากเงินสำหรับการเผา",
  no_data_found: "ไม่พบข้อมูล",
  disconnect_wallet: "ตัดการเชื่อมต่อกระเป๋าเงิน",
  confirm_trans: "ยืนยันการทำธุรกรรม",
  confirm: "กรุณายืนยันการทำรายการป๊อปอัพ",
  okay: "ตกลง",
  waiting_trans: "รอรายการยืนยัน...",
  wait: "โปรดรอ",
  confirmed: "ยืนยันธุรกรรมแล้ว!",
  products: "ผลิตภัณฑ์",
  eco_system: "ระบบนิเวศ",
  about: "เกี่ยวกับ",
  blog: "บล็อก",
  launch_to_app: "เปิดตัวแอป",
  header_title: "การดำเนินการที่สมบูรณ์แบบสำหรับโทเคนของคุณ!",
  header_description: "เราให้คุณเข้าถึงผลตอบแทน DeFi ที่ดีที่สุด งานหนักอยู่ที่เรา คุณแค่รับผลลัพธ์เท่านั้น",
  total_burnt: "ยอดรวมการเผาทั้งหมด",
  gymnet_price: "ราคา GYMNET",
  total_supply: "ยอดรวมอุปทาน",
  total_value_locked: "ยอดรวมมูลค่าที่ถูกล็อก",
  listed_on: "GYMNET อยู่ในรายการ",
  listed_on_title: "GYMNET อยู่ในรายการ",
  investment_system_title: "Gym Network — ระบบการลงทุนผู้รวบรวม DeFi",
  investment_system_description: "เครือข่าย GYM เป็นระบบการลงทุนของผู้รวบรวม DeFi ที่รวมผลตอบแทนที่ดีที่สุดและผลตอบแทนสูงสำหรับผู้ใช้ ช่วยให้คุณเข้าถึงได้ง่ายและประหยัดเวลาอันมีค่า ลองนึกภาพว่าได้ผลตอบแทนดีที่สุดจากพื้นที่ DeFi เข้าสู่กระเป๋าเงินของคุณโดยตรง ถึงเวลาแล้วที่จะทำให้ความฝันของคุณเป็นจริง!",
  go_to_the_products: "ไปที่ผลิตภัณฑ์",
  gymstreet_title: "GYM Street — เมตาเวิร์ส ",
  gymstreet_description: "สถานที่ที่เราสามารถทำได้ทุกอย่าง! เราสร้าง GYM Street เป็นอนาคตของชีวิตประจำวันของเรา งาน การเงิน การช็อปปิ้ง การสื่อสาร อสังหาริมทรัพย์ สรุปชีวิตใหม่ในเมตาเวิร์ส ค้นพบศักยภาพที่เหนือจินตนาการของคุณและออกแบบชีวิตใหม่ของคุณในเมตาเวิร์สกับ GYM Street",
  go_to_gymstreet: "ไปที่ GYM Street",
  metaverse_desc: "เราเห็นโลกที่ทุกคนเป็นส่วนหนึ่งของอนาคตดิจิทัลและกำหนดอิสรภาพทางการเงินของตนเองได้ในฐานะนักลงทุน ด้วยแรงผลักดันจากความหลงใหลในบล็อกเชน DeFi และเมตาเวิร์ส เรากำลังสร้างโซลูชันสำหรับวันพรุ่งนี้",
  protection_tools: "เครื่องมือป้องกัน",
  price_stabilizer: "ตัวปรับราคา",
  stabilizer_desc: "10% ของกำไรจากห้องนิรภัยใช้สำหรับโปรแกรมซื้อกลับและเผา",
  gym_network_title: "วิธีเริ่มต้นใช้งานเครือข่าย GYM",
  watch_tutorial: "ดูบทช่วยสอน",
  affiliate_system_title: "ระบบเครือข่ายพันธมิตร GYM",
  affiliate_system_info: "ด้วยระบบพันธมิตรของ GYM Network คุณสามารถสร้างธุรกิจอ้างอิงคริปโตของคุณเองและรายได้แบบพาสซีฟในระยะยาว",
  affiliate_desc: "มาเป็นส่วนหนึ่งของชุมชน GYM Network วันนี้และสร้างอิสรภาพทางการเงินของคุณเอง",
  read_more: "อ่านเพิ่มเติม",
  roadmap_title: "แผนงานของ GYM Network",
  roadmap_desc: "วิสัยทัศน์ของเราสำหรับอนาคตและสิ่งที่เราได้ดำเนินการมาจนถึงปัจจุบัน",
  faq: "คำถามที่พบบ่อย",
  join_telegram_group: "เข้าร่วมกลุ่ม Telegram ของเรา",
  join_telegram_group_desc: "รับข่าวสารล่าสุดและคำตอบสำหรับคำถามของคุณเกี่ยวกับ GYM Network!",
  join_now: "เข้าร่วมตอนนี้",
  footer_info: "การรวมระบบการลงทุนเมตาเวิร์สและเครื่องรวบรวม DeFi ผลตอบแทนมหาศาลใน DeFi การทำฟาร์มผลผลิต การวางเดิมพัน NFTและอื่น ๆ",
  affiliate_system: "ระบบพันธมิตร",
  gym_network: "Gym Network",
  privacy_policy: "นโยบายความเป็นส่วนตัว",
  whitepaper: "กระดาษสีขาว",
  trans_success: "ยืนยันธุรกรรมสำเร็จแล้ว!",
  unlock_and_stake: "ปลดล็อกและวางเดิมพัน",
  deposit_to_sp: "ฝากเข้ากองทุนเดี่ยว",
  failed: "การทำธุรกรรมล้มเหลว",
  unlock_staking: "ปลดล็อกการวางเดิมพัน",
  no_deposit_fee_for_burn: "ไม่มีค่าธรรมเนียมการฝากสำหรับการเผา",
  no_apy: "ไม่มีอัตราผลตอบแทนต่อปี",
  unlocked: "ปลดล็อกแล้ว",
  terms_conditions: "ข้อตกลงและเงื่อนไข",
  enter_your_email: "กรอกอีเมลของคุณ",
  verify_email: "ตรวจสอบอีเมล",
  heading: "หัวเรื่อง",
  your_sponsor_id: "ID ผู้สนับสนุนของคุณ",
  terms_condition_accept_info: "หลังจากยอมรับข้อตกลงและเงื่อนไขแล้ว คุณจะไม่สามารถเปลี่ยนแปลงได้ในภายหลังและจะดำเนินการโดยอัตโนมัติ",
  accept_terms_conditions: "ยอมรับข้อกำหนดและเงื่อนไข",
  email: "อีเมล",
  confirm_your_email: "ยืนยันอีเมลของคุณ",
  create_account: "สร้างบัญชี",
  email_verification: "ส่งรหัสยืนยันอีเมลไปที่",
  change_email: "เปลี่ยนอีเมล",
  resend_code: "ส่งรหัสอีกครั้งใน",
  turnovers: "ผลประกอบการ",
  qualified_level_vault: "ห้องนิรภัยระดับที่ผ่านการรับรอง",
  unlimited_depth_vault: "ห้องนิรภัยลึกไม่จำกัด",
  qualified_level_farm: "ฟาร์มระดับคุณภาพ",
  unlimited_depth_farm: "ฟาร์มลึกไม่จำกัด ",
  qualified_depth_single_pool: "กองทุนเดี่ยวลึกที่ผ่านการรับรอง",
  unlimited_depth_single_pool: "กองทุนเดี่ยวลึกไม่จำกัด",
  deposit_partners_list: "รายชื่อพันธมิตรโดยตรง",
  own_vault_deposit: "เงินฝากห้องนิรภัยของตัวเอง",
  level_rank: "ระดับ / อันดับ",
  total_deposit_vault: "ยอดรวมห้องนิรภัยเงินฝาก",
  total_liquidity_mining: "ยอดรวมการขุดสภาพคล่อง",
  total_single_pool: "ยอดรวมกองทุนเดี่ยว",
  total_partners: "ยอดรวมพันธมิตร",
  total_pool_rewards: "ยอดรวมกองทุนรางวัล",
  total_participants: "ยอดรวมผู้เข้าร่วม",
  unclaimed_gymnet_rewards: "รางวัล GYMNET ที่ไม่ได้รับ",
  level_pool: "ระดับกองทุน",
  vaults_contribution: "ผลงานห้องนิรภัย",
  single_contribution: "ผลงานเดี่ยว",
  farming_contribution: "ผลงานการทำฟาร์ม",
  current_pending_rewards: "รางวัลที่รอดำเนินการในปัจจุบัน",
  participants: "ผู้เข้าร่วม",
  unclaimed_rewards: "รางวัลที่ไม่ได้รับ",
  type: "ประเภท",
  txId: "ID Tx ",
  amount_before: "จำนวนเงินก่อนหน้า",
  amount_after: "จำนวนเงินหลังจาก",
  next_distribution: "การกระจายครั้งต่อไป",
  ROI_at_current_stake: "ผลตอบแทนจากการลงทุนที่วางเดิมพันปัจจุบัน",
  received_gGymnet: "รับ GYMNET แล้ว",
  about_voting_rights: "เกี่ยวกับสิทธิในการออกเสียง",
  you_successfully_verified_your_email: "คุณยืนยันอีเมลของคุณสำเร็จแล้ว",
  to_dashboard: "ไปที่แดชบอร์ด",
  you_will_receive_your_tokens_text: "คุณจะได้รับโทเคนของคุณใน Wrapped BNB โปรดนำเข้า WBNB ไปยังกระเป๋าเงินของคุณเพื่อดูเงินของคุณ",
  you_will_receive_your_tokens_text_BUSD: "คุณจะได้รับโทเคนของคุณเป็น BUSD โปรดนำเข้า BUSD ไปยังกระเป๋าเงินของคุณเพื่อดูเงินของคุณ",
  share_of_NFT_pool: "หุ้นของกองทุน NFT",
  partner_area: "พื้นที่พันธมิตร",
  rockstar_rank_text: "ร็อคสตาร์เป็นตัวเลือกคุณสมบัติเพิ่มเติม ซึ่งช่วยให้ทุกคนมีคุณสมบัติสำหรับสามอันดับที่แตกต่างกันในวิธีที่ง่ายกว่า ",
  rockstar_ranks: "อันดับร็อคสตาร์",
  to_reach_rank_you_need: "ในการไปถึงอันดับ {level} ({name}) คุณต้อง:",
  all_ranks: "ทุกอันดับ",
  reach_levels_much_easier: "เข้าถึงระดับ 102324 ได้ง่ายขึ้นมาก!",
  reach_levels_much_easier_text: "คุณสามารถจ่ายค่าธรรมเนียมการซื้อและเผา 4% ตอนนี้และเข้าถึงระดับในอนาคตภายใต้เงื่อนไขใหม่ ข้อเสนอมีอายุ 30 วันหลังจากการยืนยันข้อตกลงและเงื่อนไข",
  rockstar_10_rank: "ร็อคสตาร์ 10 อันดับ",
  rockstar_10_rank_text: "คุณจะต้องใช้เพียง 7500 USD แทน 22000 USD ในการฝากทั้งหมด นอกจากนี้คุณจะต้องฝากเงินน้อยกว่าสำหรับอันดับที่ 9 ไม่มีข้อกำหนดของพันธมิตรที่ผ่านการรับรอง",
  single_pool_deposit: "เงินฝากกองทุนเดี่ยว",
  vault_deposit: "เงินฝากห้องนิรภัย",
  farming_deposit: "เงินฝากทำฟาร์ม",
  next: "ต่อไป",
  sponsor_id: "ID ผู้สนับสนุน",
  back: "กลับ",
  ggymnet_amt: "จำนวน gGymnet",
  skip_guide: "ข้ามคำแนะนำ",
  total_amount: "ยอดรวมจำนวนเงิน",
  rockstar10_23_24_ranks: "ร็อคสตาร์ 10 23 24 อันดับ",
  rockstar_24_rank: "ร็อคสตาร์ 24 อันดับ",
  rockstar_24_rank_text: "คุณจะต้องใช้เงินเพียง 100000 USD แทน 135000 USD ในการฝากทั้งหมด ไม่มีข้อกำหนดของพันธมิตรที่ผ่านการรับรอง",
  rockstar_23_rank: "ร็อคสตาร์ 23 อันดับ",
  rockstar_23_rank_text: "คุณจะต้องใช้เพียง 90000 USD แทน 120000 USD ในการฝากทั้งหมด นอกจากนี้คุณจะต้องฝากเงินน้อยกว่าสำหรับอันดับที่ 21 22 ไม่มีข้อกำหนดของพันธมิตรที่ผ่านการรับรอง",
  swap: "แลกเปลี่ยน",
  member: "สมาชิก",
  buy: "ซื้อ",
  choose_crypto_wallet: "เลือกกระเป๋าเงินคริปโต",
  choose_crypto_wallet_desc: "เช่น MetaMask หรือ Trust Wallet",
  transfer_bnb: "โอน BNB",
  transfer_bnb_desc: "ไปยังกระเป๋าเงินของคุณ",
  connect_your_wallet: "เชื่อมต่อกระเป๋าเงินของคุณ",
  connect_your_wallet_desc: "ไปที่เว็บไซต์และทำการฝากเงินครั้งแรกของคุณในห้องนิรภัย (จาก 0.051 BNB)",
  ar_app_desc: "ความเป็นจริงยิ่งตรงกับบล็อกเชน! ฝึกฝนในโรงยิมเสมือนพร้อมรับรางวัลสำหรับการทำแบบฝึกหัด",
  ar_app: "แอป AR",
  ntf_marketplace_desc: "ลงทุน รวบรวม และแลกเปลี่ยน NFT ที่มีค่าบน zuckerland.io ซึ่งเป็นตลาดซื้อขาย NFT",
  ntf_marketplace: "ตลาด NFT",
  play_earn_desc: "เล่นเกมออนไลน์และรับรางวัล เช่น ลอตเตอรีไม่ขาดทุน ลอตเตอรีแบบ DeFi ที่ไม่เหมือนใคร",
  play_earn: "เล่นและรับ",
  launchpad_desc: "เป็นคนแรกที่จะได้เข้าถึงโครงการใหม่ก่อนที่จะออกสู่ตลาด",
  launchpad: "Launchpad",
  earn_crypto_desc: "รับผลตอบแทนที่น่าสนใจจาก Bitcoin ETH BNB DOGE Stablecoins และอีกมากมาย",
  earn_crypto: "รับคริปโต",
  gymnet_vault_desc: "รับผลประโยชน์สูงสุดในสินทรัพย์คริปโตยอดนิยมและรับรางวัลโทเคนที่ไม่เหมือนใคร",
  gymnet_vault: "ห้องนิรภัย Gymnet",
  metaverse: "เมตาเวิร์ส",
  metaverse_slide_desc: "ซื้อที่ดินเพื่อเข้าถึงผลิตภัณฑ์ในอนาคตทั้งหมดโดยเฉพาะและใช้ในโลกเสมือนจริง\n",
  yield_farming_desc: "ค้นหาข้อเสนอการทำฟาร์มที่ดีที่สุดและให้ผลกำไรมากที่สุดใน DeFi",
  yield_farming: "การทำฟาร์มผลผลิต",
  farming: "การทำฟาร์ม",
  farm_sp: "4% ของฟาร์มและกองทุนเดี่ยว ",
  farm_sp_desc: "เงินฝากเข้าสู่โปรแกรมซื้อคืนและเผาเพื่อต่อต้านเงินเฟ้อ",
  locking_sp: "ล็อกในกองทุนเดียว",
  locking_sp_desc: "ลดการหมุนเวียนของ GYMNET ซึ่งช่วยให้ราคามีเสถียรภาพในระยะยาว",
  burning_gymnet: "การเผา GYMNET",
  burning_gymnet_desc: "การซื้อคืนและการเผาจะส่งผลให้ราคา GYMNET เพิ่มขึ้นและการขายโทเคนลดลง ",
  through_codetermination_rights: "ด้วยการกำหนดสิทธิร่วมกัน",
  through_codetermination_rights_desc: "ชุมชนมีผลกระทบโดยตรงต่ออนาคตของ GYM Network ",
  single_pool: "กองทุนเดี่ยว",
  buy_GYMNET: "ซื้อ GYMNET",
  gymstreet: "Gymstreet",
  metablocks: "เมตาบล็อก",
  cashFT: "CashFT",
  zuckerland: "ซัคเกอร์แลนด์",
  metaverse_campus: "วิทยาเขตเมตาเวิร์ส",
  blog_news: "บล็อกและข่าวสาร",
  support: "สนับสนุน",
  newsletter: "จดหมายข่าว",
  documentation: "เอกสาร",
  smart_contract: "สัญญาอัจฉริยะ",
  community: "ชุมชน",
  guide: "แนะนำ",
  help: "ช่วยเหลือ",
  certik: "ตรวจสอบโดย CERTIK!",
  stability_program: "โปรแกรมเสถียรภาพ GYMNET",
  audited: "ตรวจสอบแล้ว",
  our_official_telegram: "Telegram อย่างเป็นทางการของเรา",
  official_partner: "พันธมิตรอย่างเป็นทางการ",
// ...................

tokenContract: "Token Contract",
gymDex:"Gym Dex",

}
