export default {
  dashboard: "仪表板",
  my_dashboard: '我的仪表板',
  balance: '结余',
  connect_wallet: '连接钱包',
  learn_more: '学到更多',
  wallet: '钱包',
  max: '最大额度',
  min_amount: '最低金额',
  you_will_need_bnb_in_your_wallet: '你的钱包里需要有BNB',
  usd: '美元',
  apy: '年利率',
  total_staked: '总赌注',
  daily_rewards: '每日奖励',
  weekly_rewards: '每周奖励',
  pool_statistics: '池统计',
  monthly_rewards: '每月奖励',
  my_deposit: '我的存款',
  share_of_pool: '共享池',
  my_vaults: '我的金库',
  exchange: '交换',
  staked_amount: '质押金额',
  claimed_amount: '索赔金额',
  total_growth: '总增长',
  total_stakers: '总质押者',
  deposit: '订金',
  team: '团队',
  referral_link: '推荐链接',
  current_rank: '当前等级',
  partners: '伙伴',
  level_name: '级别名称',
  own_active_gymnet_farm: '拥有活跃的GYMNET农场',
  to_reach_next_rank: '达到下一个等级',
  direct: '直接的',
  own_deposit: '自己的存款',
  gained: '获得',
  rank: '等级',
  reward: '报酬',
  all: '全部',
  my: '我的',
  required_partners: '必需的合作伙伴',
  statistic_rewards: '统计奖励',
  own_single_pool_needed: '需要自己的单池',
  unlocked_ranks: '解锁等级',
  invested: '投资',
  connect_to_wallet: '连接到钱包',
  choose_wallet: '选择钱包',
  i_read_and_accept: '我已阅读并接受',
  accept_term_and_condition: '接受<span class="primary-color">服务</span>和<span class="primary-color">隐私政策</span>的条款',
  company_icon: '公司图标',
  beidge_icon: 'Beidge图标',
  total_vaults_deposit: '金库存款总额',
  total_income: '总收入',
  gymnet_earned: 'GYMNET赚了',
  investment: '投资',
  your_address: '你的地址',
  manage_wallets: '管理钱包',
  wallet_icon: '钱包图标',
  copy_icon: '复制图标',
  history: '历史',
  time_icon: '时间图标',
  view_on_bscScan: '在 BscScan 上查看',
  redirect_icon: '重定向图标',
  the_referral_system_and_the_profit_commissions: '推荐系统有25个级别，每个级别的利润佣金显示如下：',
  the_referral_system_and_the_profit_commissions_description1: '当您有资格获得第 14、15 或 16 级时，您还将参与全球池份额。在这种情况下，无论您自己的团队结构如何，您都将获得整个 GYM NETWORK 产生的整体利润和奖励的一部分。例如，如果您是 16 级，则您有资格获得白金奖池。在这种情况下，您将获得分配给会员系统的 GYM NETWORK 范围内利润和奖励的 1.5% 的份额。',
  the_referral_system_and_the_profit_commissions_description2: '只要您赞助的合作伙伴在 GYM NETWORK 中保持活跃，您就可以赚取佣金，这实际上相当于一个不错的被动收入流。帮助其他人通过 DeFi 获利，并以此赚取被动收入。',
  turnover_pool_monthly: '每月营业额池',
  level_pool_daily: '每日水平池',
  regional: '区域',
  national: '国家的',
  international: '国际的',
  gold: '金子',
  level: '等级',
  platin: '铂金的',
  black: '黑色的',
  vault: '金库',
  strategy: '战略',
  vaults: '金库',
  tokens: '代币',
  gymnet_icon: '健身房图标',
  total_gymnet_vaults_rewards: 'GYMNET 金库总奖励',
  claim_all: '索赔全部',
  all_vaults: '所有的金库',
  coming_soon: '快来了',
  rewards: '奖励',
  claim: '索赔',
  vaultCommissions: '金库佣金',
  farmingCommissions: '农业委员会',
  singlePoolCommissions: '单池佣金',
  vaultCommissionsTotal: '金库佣金总额',
  totalInvestorsProfit: '投资者总利润',
  pendingCommissions: '待定佣金',
  commissionsFromVaultInvestors: '来自金库投资者的佣金',
  partnerActivity: '合作伙伴活动',
  date: '日期',
  user: '用户',
  amount: '数量',
  token: '代币',
  tx: '德克萨斯州',
  loadMore: '加载更多',
  dailyROI: '每日投资回报率',
  hourlyROI: '每小时投资回报率',
  totalLiquidity: '总流动性',
  totalTokensLocked: '锁定的总代币',
  viewContract: '查看合同',
  seePairInfo: '查看配对信息',
  myStake: '我的赌注',
  myStakeText: '在这里您可以存入您的 GYMNET 代币以获得更多奖励',
  addLiquidityStake: '增加流动性和权益',
  gymnetEarned: 'Gymnet赚了',
  claimStake: '索赔和赌注',
  addLiquidutyStake: '添加流动性和赌注',
  gymnetAndBnb: 'gymnet 和 bnb',
  gymnetAndBusd: 'gymnet 和 busd',
  gymnet: '体操网',
  bnb: 'bnb',
  withdraw: '提取',
  balanceNum: '余额：ß{n}',
  claim_and_farm: '索赔和农场',
  compound_your_gymnet: '收取你的 GYMNET',
  claimAndFarm: '索赔和农场',
  your_total_deposit: '您的总存款',
  total_pending_rewards: '总待定奖励',
  total_own_claimed: '总共拥有的索赔',
  active_holdings: '主动持股',
  archived_holdings: '存档资产',
  with_locking_period: '有锁定周期',
  without_locking_period: '无锁定周期',
  deposit_amount: '存款金额',
  pending_rewards: '待定奖励',
  you_dont_receive_pending_rewards_for_deposit_without_locking_period: '没有锁定期的存款，您不会收到待定奖励',
  lpTokensWillBeAutomaticallyStakedOnTheFaringContract: 'LP 代币将自动质押在票价合约上。',
  depositFeeForBuyAndBurn: '购买和销毁的 4% 存款费',
  unlock: '不锁定',
  halfOfYourGymNetTokensWillBeUsed: '您一半的 GYMNET 代币将用于购买 BNB，然后汇集并在质押联系人上质押。',
  halfOfYourBnbTokensWillBeUsed: '您一半的 BNB 代币将用于购买 GYMNET，然后汇集并在质押联系人上质押。',
  removeLiquidity: '去除流动性',
  pooled: '汇集',
  unstake: '取消抵押',
  lpTokensWillBeInYourWallet: 'LP 代币将在您的钱包中。要获得 BNB 和 GYMNET 代币，请在完成此操作后单击 移除流动性 按钮',
  dailyProfit: '每日利润',
  withdraw_and_claim: '撤回和索赔',
  pending_GYMNET_reward: '等待 GYMNET 奖励',
  LP_tokens_will_be_in_your_wallet: 'LP 代币将在您的钱包中。要获得 BNB 和 GYMNET 代币，请在完成此操作后单击 移除流动性 按钮',
  claim_and_deposit_to_sp: '索取并存入单池',
  claim_and_deposit: '索赔和存款',
  deposit_with_locking_period: '锁定期存款',
  claimAndDeposit: '索赔和存款',
  depositWithLockingPeriod: '锁定期存款',
  confirmLockingPeriod: '确认锁定期',
  total_gymnet_locked_in_pool: '总 GYMNET 锁定在池中',
  total_claimed: '索赔总额',
  reward_per_block: '每块奖励',
  start_date: '开始日期',
  end_date: '结束日期',
  launch_of: '推出',
  locked: '锁定',
  months: '几个月',
  nothing_to_show: '无内容',
  you_will_receive_commissions_text: '您将从您的下线获得佣金，并将根据排名条件获得资格',
  deposit_fee_for_burn: '烧伤押金',
  no_data_found: '无数据',
  disconnect_wallet: '断开钱包',
  confirm_trans: '确认交易',
  confirm: '请确认弹出的交易。',
  okay: '好的',
  waiting_trans: '等待交易确认...',
  wait: '请稍等',
  confirmed: '交易确认！',
  products: '产品',
  eco_system: '生态系统',
  about: '关于',
  blog: '博客',
  launch_to_app: '启动应用程序',
  header_title: '代币的完美应用！',
  header_description: '我们让你获得最好的 DeFi 回报。我们努力工作，你只需要获取结果。',
  total_burnt: '完全烧毁',
  gymnet_price: '健身房价格',
  total_supply: '总供应量',
  total_value_locked: '总价值锁定',
  listed_on: 'GYMNET 上市',
  listed_on_title: 'GYMNET 上市',
  investment_system_title: 'Gym Network — DeFi 聚合器投资系统',
  investment_system_description: 'GYM Network 是一个 DeFi 聚合投资系统，它结合了最佳收益和为其用户提供的高额回报。从而提供方便的访问并为您节省大量宝贵的时间。想象一下，将 DeFi 领域的最佳收益直接存入您的钱包。现在是时候让你的梦想变成现实了！',
  go_to_the_products: '查看产品',
  gymstreet_title: '健身房街 - 元宇宙',
  gymstreet_description: '一个我们可以做任何事情的地方！我们将 GYM Street 打造为我们日常生活的未来。工作、金融、购物、通讯、置业，整合元宇宙的新生活。发现你无法想象的潜力，在 GYM Street 的元宇宙设计你的新生活。',
  go_to_gymstreet: '去健身街',
  metaverse_desc: "我们看到一个世界，每个人都是数字未来的一部分，并且可以作为投资者塑造自己的财务自由。在我们对区块链、DeFi 和元宇宙的热情的推动下，我们正在创造明天的解决方案'。",
  protection_tools: '保护工具',
  price_stabilizer: '价格稳定器',
  stabilizer_desc: '来自金库10% 的利润用于回购和销毁计划。',
  gym_network_title: '如何开始使用 GYM 网络',
  watch_tutorial: '观看教程',
  affiliate_system_title: 'GYM网络会员系统',
  affiliate_system_info: '通过 GYM Network 的会员系统，您可以建立自己的加密推荐业务和长期被动收入。',
  affiliate_desc: '今天成为 GYM Network 社区的一员，并创造你自己的财务自由。',
  read_more: '阅读更多',
  roadmap_title: 'GYM 网络路线图',
  roadmap_desc: '我们对未来的愿景以及我们迄今为止已经达成的',
  faq: '常见问题',
  join_telegram_group: '加入我们的电报群',
  join_telegram_group_desc: '获取关于 GYM Network 的所有最新问题和答案！',
  join_now: '现在加入',
  footer_info: '元宇宙与 DeFi 聚合投资系统的结合。 DeFi、Yield Farming、Staking、NFT 等方面的丰厚回报。',
  affiliate_system: '附属系统',
  gym_network: '健身房网络',
  privacy_policy: '隐私政策',
  whitepaper: '白皮书',
  trans_success: '交易成功确认！',
  unlock_and_stake: '解除锁定和质押',
  deposit_to_sp: '存入单池',
  failed: '交易失败',
  unlock_staking: '解锁质押',
  no_deposit_fee_for_burn: '烧毁不收取押金',
  no_apy: '没有收益率',
  unlocked: '解锁',
  terms_conditions: '条款和细则',
  enter_your_email: '输入你的电子邮箱',
  verify_email: '验证邮件',
  heading: '标题',
  your_sponsor_id: '您的赞助商 ID',
  terms_condition_accept_info: '接受T&C后，以后将无法更改，将自动执行。',
  accept_terms_conditions: '接受条款和条件',
  email: '电子邮件',
  confirm_your_email: '确认您的电子邮件',
  create_account: '创建账户',
  email_verification: '电子邮件验证码已发送至',
  change_email: '更改电子邮件',
  resend_code: '重新发送代码',
  turnovers: '营业额',
  qualified_level_vault: '符合资质水平的金库',
  unlimited_depth_vault: '无限深度金库',
  qualified_level_farm: '合格的农场',
  unlimited_depth_farm: '无限深度农场',
  qualified_depth_single_pool: '合格的深度单池',
  unlimited_depth_single_pool: '无限深度单池',
  deposit_partners_list: '直接合作伙伴名单',
  own_vault_deposit: '自己的金库存款',
  level_rank: '等级/等级',
  total_deposit_vault: '总存款金库',
  total_liquidity_mining: '总流动性挖矿',
  total_single_pool: '总单池',
  total_partners: '总合作伙伴',
  total_pool_rewards: '总池奖励',
  total_participants: '参与者总数',
  unclaimed_gymnet_rewards: '无人认领的 GYMNET 奖励',
  level_pool: '水平池',
  vaults_contribution: '金库贡献',
  single_contribution: '单一贡献',
  farming_contribution: '耕种贡献',
  current_pending_rewards: '当前待定奖励',
  participants: '参与者',
  unclaimed_rewards: '无人认领的奖励',
  type: '类型',
  txId: '区块链交易哈希',
  amount_before: '之前的金额',
  amount_after: '之后的金额',
  next_distribution: '下一次分发',
  ROI_at_current_stake: '目前的投资回报率',
  received_gGymnet: '收到 GYMNET',
  about_voting_rights: '关于投票权',
  you_successfully_verified_your_email: '您成功验证了您的电子邮件',
  to_dashboard: '到仪表板',
  you_will_receive_your_tokens_text: '您将收到BNB包裹中的代币，请将 WBNB 导入您的钱包以查看您的资金。',
  you_will_receive_your_tokens_text_BUSD: '您将收到您的 BUSD 代币，请将 BUSD 导入您的钱包以查看您的资金。',
  share_of_NFT_pool: 'NFT池派得的份额',
  partner_area: '合作伙伴区',
  rockstar_rank_text: '摇滚明星是一个额外的资格获取选项，它允许每个人以更简单的方式获得三个不同等级的资格。 ',
  rockstar_ranks: '摇滚明星排名',
  to_reach_rank_you_need: '要达到等级 {level} ({name})，您需要：',
  all_ranks: '所有等级',
  reach_levels_much_easier: '达到 10、23、24 级要容易得多！',
  reach_levels_much_easier_text: '你现在可以支付 4% 的购买和销毁费用，并在新的条件下达到未来的水平。优惠在确认 T&C 确认后 30 天内有效。',
  rockstar_10_rank: '摇滚明星 10 级',
  rockstar_10_rank_text: '您在所有存款中只需要 7500 美元而不是 22000 美元。此外，您将需要较小的存款才能获得 9 级。没有合格的合作伙伴要求。',
  single_pool_deposit: '单池存款',
  vault_deposit: '金库存款',
  farming_deposit: '耕种存款',
  next: '下一个',
  sponsor_id: '赞助商ID',
  back: '后退',
  ggymnet_amt: 'gGymnet 金额',
  skip_guide: '跳过指南',
  total_amount: '总金额',
  rockstar10_23_24_ranks: 'Rockstar 10， 23， 24 排名',
  rockstar_24_rank: '摇滚明星 24 级',
  rockstar_24_rank_text: '您在所有存款中只需要 100000 美元而不是 135000 美元。没有合格的合作伙伴要求。',
  rockstar_23_rank: '摇滚明星 23 级',
  rockstar_23_rank_text: '您在所有存款中只需要 90000 美元而不是 120000 美元。此外，21、22 等级您将需要较小的存款。没有合格的合作伙伴要求。',
  swap: '交换',
  member: '成员',
  buy: '买',
  choose_crypto_wallet: '选择一个加密钱包',
  choose_crypto_wallet_desc: '像 MetaMask 或 Trust Wallet',
  transfer_bnb: '转移 BNB',
  transfer_bnb_desc: '到你的钱包',
  connect_your_wallet: '连接你的钱包',
  connect_your_wallet_desc: '到网站并在金库中进行第一笔存款（从 0.051 BNB 起）',
  ar_app_desc: '增强现实遇到区块链！在虚拟健身房训练，同时获得完成练习的奖励',
  ar_app: 'AR 应用程序',
  ntf_marketplace_desc: '在 NFT 市场 zuckerland.io 上投资、收集和交易有价值的 NFT。',
  ntf_marketplace: 'NFT 市场',
  play_earn_desc: '玩在线游戏并获得奖励，例如无损彩票，是一种绝对独特的基于 DeFi 的彩票',
  play_earn: '玩乐和赚钱',
  launchpad_desc: '在新项目进入市场之前成为第一批获得新项目的人',
  launchpad: '发射台',
  earn_crypto_desc: '通过比特币、ETH、BNB、DOGE、稳定币等获得可观的回报。',
  earn_crypto: '赚取加密货币',
  gymnet_vault_desc: '在最受欢迎的加密资产中获得最大利益并获得独特的代币奖励',
  gymnet_vault: '健身房金库',
  metaverse: '元宇宙',
  metaverse_slide_desc: '购买土地以获得对所有未来产品的独家访问权并在我们的虚拟世界中使用它们\n',
  yield_farming_desc: '在 DeFi 中找到最好、最赚钱的农业交易',
  yield_farming: '高产农田',
  farming: '正在耕种',
  farm_sp: '4% 的农场和单池',
  farm_sp_desc: '存款进入回购和销毁计划以抵消通货膨胀。',
  locking_sp: '锁定在单池',
  locking_sp_desc: '减少流通中的 GYMNET，这有助于长期稳定价格。',
  burning_gymnet: '正在燃烧的GYMNET',
  burning_gymnet_desc: '通过回购和销毁将导致 GYMNET 价格上涨和代币销售减少。 ',
  through_codetermination_rights: '通过共同决定权',
  through_codetermination_rights_desc: '社区对 GYM Network 的未来有着直接的影响。 ',
  single_pool: '单池',
  buy_GYMNET: '购买 GYMNET',
  gymstreet: '体育馆街',
  metablocks: '元宇宙块',
  cashFT: 'CashFT',
  zuckerland: '萨克地',
  metaverse_campus: '元宇宙校园',
  blog_news: '博客与新闻',
  support: '支持',
  newsletter: '通讯',
  documentation: '文件',
  smart_contract: '智能合约',
  community: '社区',
  guide: '指导',
  help: '帮助',
  certik: '经 CERTIK 审核！',
  stability_program: 'GYMNET 稳定计划',
  audited: '经审核',
  our_official_telegram: '我们的官方电报',
  official_partner: '官方合作伙伴',

// ............................

tokenContract: "Token Contract",
gymDex:"Gym Dex",
}
