export default {
  contract_address: "合约地址",
  audited: '经审核',
  our_official_telegram: '我们的官方电报',
  official_partner: '官方合作伙伴',
  products: '产品',
  eco_system: '生态系统',
  about: '关于',
  blog: '博客',
  launch_to_app: '启动应用程序',
  header_title: '代币的完美应用！',
  header_description: '我们让你获得最好的 DeFi 回报。我们努力工作，你只需要获取结果。',
  total_burnt: '完全烧毁',
  gymnet_price: '健身房价格',
  total_supply: '总供应量',
  total_value_locked: '总价值锁定',
  header_info: "前社区成员可以使用 <a href='http://old.gymnetwork.io/dashboard/community-transfer/' target='_blank' class='fw-bold'> 开始迁移 </a> 链接将他们的资产和资产转移到新版本。",
  listed_on_title: 'GYMNET 上市',
  investment_system_title: 'Gym Network — DeFi 聚合器投资系统',
  investment_system_description: 'GYM Network 是一个 DeFi 聚合投资系统，它结合了最佳收益和为其用户提供的高额回报。从而提供方便的访问并为您节省大量宝贵的时间。想象一下，将 DeFi 领域的最佳收益直接存入您的钱包。现在是时候让你的梦想变成现实了！',
  go_to_the_products: '查看产品',
  gymstreet_title: '健身房街 - 元宇宙',
  gymstreet_description: '一个我们可以做任何事情的地方！我们将 GYM Street 打造为我们日常生活的未来。工作、金融、购物、通讯、置业，整合元宇宙的新生活。发现你无法想象的潜力，在 GYM Street 的元宇宙设计你的新生活。',
  go_to_gymstreet: '去健身街',
  metaverse_desc: "我们看到一个世界，每个人都是数字未来的一部分，并且可以作为投资者塑造自己的财务自由。在我们对区块链、DeFi 和元宇宙的热情的推动下，我们正在创造明天的解决方案'。",
  stability_program: 'GYMNET 稳定计划',
  farm_sp: '4% 的农场和单池',
  farm_sp_desc: '存款进入回购和销毁计划以抵消通货膨胀。',
  locking_sp: '锁定在单池',
  locking_sp_desc: '减少流通中的 GYMNET，这有助于长期稳定价格。',
  burning_gymnet: '正在燃烧的GYMNET',
  burning_gymnet_desc: '通过回购和销毁将导致 GYMNET 价格上涨和代币销售减少。 ',
  through_codetermination_rights: '通过共同决定权',
  through_codetermination_rights_desc: '社区对 GYM Network 的未来有着直接的影响。 ',
  gym_network_title: '如何开始使用 GYM 网络',
  choose_crypto_wallet: '选择一个加密钱包',
  choose_crypto_wallet_desc: '像 MetaMask 或 Trust Wallet',
  transfer_bnb: '转移 BNB',
  transfer_bnb_desc: '到你的钱包',
  connect_your_wallet: '连接你的钱包',
  connect_your_wallet_desc: '到网站并在金库中进行第一笔存款（从 0.051 BNB 起）',
  watch_tutorial: '观看教程',
  coming_soon: '快来了',
  roadmap_title: 'GYM 网络路线图',
  roadmap_desc: '我们对未来的愿景以及我们迄今为止已经达成的',
  ar_app_desc: '增强现实遇到区块链！在虚拟健身房训练，同时获得完成练习的奖励',
  ar_app: 'AR 应用程序',
  ntf_marketplace_desc: '在 NFT 市场 zuckerland.io 上投资、收集和交易有价值的 NFT。',
  ntf_marketplace: 'NFT 市场',
  play_earn_desc: '玩在线游戏并获得奖励，例如无损彩票，是一种绝对独特的基于 DeFi 的彩票',
  play_earn: '玩乐和赚钱',
  launchpad_desc: '在新项目进入市场之前成为第一批获得新项目的人',
  launchpad: '发射台',
  earn_crypto_desc: '通过比特币、ETH、BNB、DOGE、稳定币等获得可观的回报。',
  earn_crypto: '赚取加密货币',
  gymnet_vault_desc: '在最受欢迎的加密资产中获得最大利益并获得独特的代币奖励',
  gymnet_vault: '健身房金库',
  metaverse: '元宇宙',
  metaverse_slide_desc: '购买土地以获得对所有未来产品的独家访问权并在我们的虚拟世界中使用它们\n',
  yield_farming_desc: '在 DeFi 中找到最好、最赚钱的农业交易',
  yield_farming: '高产农田',
  faq: '常见问题',
  read_more: '阅读更多',
  learn_more: '学到更多',


  // .................     start Questions  ...........................................

  what_defi: "什么是 DeFi？",
  what_defi_desc:
    `
    <p> DeFi 代表“去中心化金融”，是描述加密货币或区块链中各种金融应用的总称——这使得银行等金融中介机构能够去中心化。 你们都知道中央金融机构是如何运作的。 他们拥有您和其他客户存入的所有资金，每当您需要向某人汇款或从银行获得贷款时，您都会经历一个漫长、官僚和乏味的过程。 除了效率低下，银行在交易费用方面收取一定比例的资金。 </p>
    <p> DeFi 所做的是让金融交易更快、更便宜，而且通常更高效 .</p>
    <p> DeFi 让人们无需相互信任即可轻松进行金融交易。 因此，DeFi 平台建立在区块链之上，并借助智能合约促进金融交易。 </p>
    <p> DeFi 允许加密货币企业家在分散的结构中重建传统金融工具，不受银行和中央当局的控制。 </p>
  `,
  what_smart_contract: "什么是智能合约？",
  what_smart_contract_desc:
    `
  <p>智能合约是充当中介的自动化应用程序。</p>
  <p>这是区块链中的一段代码，可帮助同行（人类和应用程序，如其他智能合约）在平台上进行交互，而无需相互信任。</p>
  <p>智能合约代码始终是公开可用的，这就是为什么区块链技术通常被称为“不可信”的原因。</p>
 `,
  what_liquidity_meaning: "什么是流动性挖矿？",
  what_liquidity_meaning_desc:
    `
    <p> 流动性挖矿意味着将代币添加到 DEX（去中心化交易所）的流动性池中，例如 Uniswap、Sushiswap 或 PancakeSwap。</p>
    <p> 通过向市场提供流动性，您可以让去中心化交易所发挥作用，作为回报，您将获得加密货币的回报。</p>
    <p> 为去中心化交易所增加流动性被称为“流动性挖矿”，因为它可以像挖矿比特币或以太坊等加密货币一样为您带来利润。</p>
    <p> 流动性挖矿和加密货币挖矿都是产生基于区块链的被动收入的绝佳方式。</p>
  `,
  what_liquidity_pool: "究竟什么是“流动资金池”？",
  what_liquidity_pool_desc: `当你使用像 Binance 或 Coinbase 这样的中心化交易所时，流动性由拥有交易所的公司提供。 由于去中心化交易所没有自己的储备，流动性由将自己的资金锁定在流动性池中的用户提供。 简而言之，流动性池允许你在 DEX 上买卖加密货币。`,
  what_dao: "什么是去中心化自治组织 (DAO)？",
  what_dao_desc:
    `
      <p> 去中心化自治组织 (DAO) 是在区块链上运行的软件，它为用户提供了一个内置模型，用于对其代码进行集体管理。 </p>
      <p> DAO 不同于由董事会、委员会和高管管理的传统组织。 DAO 不是由有限的群体管理，而是使用一组写在代码中的规则，并由运行共享软件的计算机网络强制执行。 </p>
      <p> 要成为 DAO 的成员，用户需要首先通过购买其加密货币来加入 DAO。 持有资产通常会赋予用户对提案和更新进行投票的权力，这与他们持有的数量成正比。 </p>
    `,
  what_dao_governance: "什么是 DAO 治理？",
  what_dao_governance_desc:
    `
      <p>DAO 治理使用授予投票权的代币或 NFT 进行协调</p>
      <p>DAO 列表仅限于验证加密货币钱包中这些监管代币所有权的人。并且可以交换会员治理是通过成员通过区块链投票的一系列提案来实现的。拥有更多监管代币通常会带来更多投票权。</p>
    `,

  how_use_network: "如何使用 GYM NETWORK？",
  how_use_network_desc:
    `
      <p> 您可以将其用作保险库、单一农场和流动性挖矿。 因此，您可以通过三种方式从代币中获得更多收益。 </p>
      <p> 与此同时，我们一直致力于 GYMNET 代币的实用性。 您持有的 GYMNET 代币越多，您就越能更好地参与未来的项目！ 请参阅 Meta-networks.io 路线图。 您将需要 GYMNET 代币才能获得独家福利并同时获得 GYMNET 奖励。 </p>
      <p> 总而言之，这意味着：您可以将 GYM NETWORK 用作 DeFi 平台，也可以用作不断发展的元界。 当然，要建立会员职业并赚取丰厚的佣金！ </p>
    `,
  which_wallet_use_to_connect: "我可以使用哪些钱包进行连接？",
  which_wallet_use_to_connect_desc: `您可以在 WALLET CONNECT 项下使用 Metamask、Trust Wallet 和所有提供的钱包。`,
  what_apy_apr: "什么是 APY 和 APR？",
  what_apy_apr_desc:
    `
     <p>APR 代表赚取或借钱的年利率。</p>
     <p>APY 考虑复利，但 APR 没有。</p>
  `,
  where_rewords_vaults_come_from: `宝库中的奖励从何而来？`,
  where_rewords_vaults_come_from_desc:
    `
      <p>每个保险库都连接到众所周知且完善的 DeFi 协议。 在这种情况下，BNB/GYMNET 保险库连接到 Alpaca 平台。</p>
      <p>例如，用户可以有息借钱。 这个好处就是你的奖励。 作为用户，您还将从我们的平台获得 GYMNET 代币作为奖励 。</p>
      <p>与没有 GYM NETWORK 的直接使用 Alpaca 的用户相比，这将为您带来优势！ 例如 </p>
   `,
  who_what_alpaca: "谁或什么是  ALPACA？",
  who_what_alpaca_desc:
    `
    <p>
      <a href='https://www.alpacafinance.org/' target='_blank'>Alpaca Finance<a/>
      是最大的借贷协议，允许在币安智能链上进行杠杆耕作，为贷方提供安全稳定的回报。 并为高回报的农业工作提供低抵押贷款。 大幅增加农业成本和后续利润。
    </p>
  `,
  what_binance: "什么是Binance Smart Chain?",
  what_binance_desc: `Binance Chain由Binance于2019年4月推出。其主要重点是促进快速、分散（或非监管）的贸易。也许不出所料，最大的分散式应用程序（或DApp）是Binance DEX，那里最友好的分散式交易所之一。您可以在binance.org通过Web界面或通过其与Trust Wallet的本机集成来使用它。`,
  what_do_with_gymnet: "我可以用GYMNET令牌做什么?",
  what_do_with_gymnet_desc:
    `
      <p>您持有的GYMNET令牌越多,您就能更好地访问未来的项目!请参阅Meta-networks.io路线图。你将需要GYMNET令牌获得独家福利，同时GYMNET奖励。</p>
      <p>使用桉例是：您可以使用GYM NETWORK及其奖励令牌GYMNET作为VAULT、Single Farm和Liquidity Mining中的DeFi平台,以及一个不断发展的元宇宙。</p>
   `,
  where_gymnet_lysted: "GYMNET令牌在哪里上市?",
  where_gymnet_lysted_desc: `你可以在CoinMarketCap和CoinGecko上找到GYMNET。它可以在PancakeSwap上交易。`,
  where_find_tutorials: "在哪里可以找到教程?",
  where_find_tutorials_desc: `您可以访问我们YouTube频道上的所有视频教程,也可以访问Gitbook上的文档。`,
  how_affiliate_work: " 联属系统如何运作?",
  how_affiliate_work_desc:
    `
      <p>联属系统直接通过你的钱包工作。每个钱包必须链接到一个电报帐户时，你注册（只有通过邀请与会员链接）。这对于支持请求非常重要,而且更重要!</p>
      <p>之后，将为您分配自己的关联链接，您可以使用该链接成为会员。如果现在有人注册并投资金库并获得奖励，你也会得到"被动"佣金。</p>
      <p>所以，每当你被推荐的投资者（你有推荐身份）决定使用GYM NETWORK并获得他的第一个VAULT奖励时，你就会得到佣金。一遍又一遍，只要用户离开他在Vault的投资。这样你就可以积累利润丰厚的被动收入。</p>
      <p>联属系统共有16个关卡和其他亮点，将帮助你开始作为一个提示！查看网络研讨会或演示文稿PDF,或联系赞助商了解更多详细信息。</p>
    `,

  // .................     end Questions  ...........................................

  join_telegram_group: '加入我们的电报群',
  join_telegram_group_desc: '获取关于 GYM Network 的所有最新问题和答案！',
  join_now: '现在加入',
  footer_info: '元宇宙与 DeFi 聚合投资系统的结合。 DeFi、Yield Farming、Staking、NFT 等方面的丰厚回报。',
  vault: '金库',
  farming: '正在耕种',
  single_pool: '单池',
  buy_GYMNET: '购买 GYMNET',
  gymstreet: '体育馆街',
  metablocks: '元宇宙块',
  cashFT: '现金FT',
  zuckerland: '萨克地',
  gymDex: "健身房Dex",
  metaverse_campus: '元宇宙校园',
  whitepaper: '白皮书',
  blog_news: '博客与新闻',
  support: '支持',
  guide: '指导',
  tokenContract: "代币合约",
  gym_network: '健身房网络',




  // ......................................................................

  //   // ...............................................................
  //   dashboard: "仪表板",
  //   my_dashboard: '我的仪表板',
  //   balance: '结余',
  //   connect_wallet: '连接钱包',

  //   wallet: '钱包',
  //   max: '最大额度',
  //   min_amount: '最低金额',
  //   you_will_need_bnb_in_your_wallet: '你的钱包里需要有BNB',
  //   usd: '美元',
  //   apy: '年利率',
  //   total_staked: '总赌注',
  //   daily_rewards: '每日奖励',
  //   weekly_rewards: '每周奖励',
  //   pool_statistics: '池统计',
  //   monthly_rewards: '每月奖励',
  //   my_deposit: '我的存款',
  //   share_of_pool: '共享池',
  //   my_vaults: '我的金库',
  //   exchange: '交换',
  //   staked_amount: '质押金额',
  //   claimed_amount: '索赔金额',
  //   total_growth: '总增长',
  //   total_stakers: '总质押者',
  //   deposit: '订金',
  //   team: '团队',
  //   referral_link: '推荐链接',
  //   current_rank: '当前等级',
  //   partners: '伙伴',
  //   level_name: '级别名称',
  //   own_active_gymnet_farm: '拥有活跃的GYMNET农场',
  //   to_reach_next_rank: '达到下一个等级',
  //   direct: '直接的',
  //   own_deposit: '自己的存款',
  //   gained: '获得',
  //   rank: '等级',
  //   reward: '报酬',
  //   all: '全部',
  //   my: '我的',
  //   required_partners: '必需的合作伙伴',
  //   statistic_rewards: '统计奖励',
  //   own_single_pool_needed: '需要自己的单池',
  //   unlocked_ranks: '解锁等级',
  //   invested: '投资',
  //   connect_to_wallet: '连接到钱包',
  //   choose_wallet: '选择钱包',
  //   i_read_and_accept: '我已阅读并接受',
  //   accept_term_and_condition: '接受<span class="primary-color">服务</span>和<span class="primary-color">隐私政策</span>的条款',
  //   company_icon: '公司图标',
  //   beidge_icon: 'Beidge图标',
  //   total_vaults_deposit: '金库存款总额',
  //   total_income: '总收入',
  //   gymnet_earned: 'GYMNET赚了',
  //   investment: '投资',
  //   your_address: '你的地址',
  //   manage_wallets: '管理钱包',
  //   wallet_icon: '钱包图标',
  //   copy_icon: '复制图标',
  //   history: '历史',
  //   time_icon: '时间图标',
  //   view_on_bscScan: '在 BscScan 上查看',
  //   redirect_icon: '重定向图标',
  //   the_referral_system_and_the_profit_commissions: '推荐系统有25个级别，每个级别的利润佣金显示如下：',
  //   the_referral_system_and_the_profit_commissions_description1: '当您有资格获得第 14、15 或 16 级时，您还将参与全球池份额。在这种情况下，无论您自己的团队结构如何，您都将获得整个 GYM NETWORK 产生的整体利润和奖励的一部分。例如，如果您是 16 级，则您有资格获得白金奖池。在这种情况下，您将获得分配给会员系统的 GYM NETWORK 范围内利润和奖励的 1.5% 的份额。',
  //   the_referral_system_and_the_profit_commissions_description2: '只要您赞助的合作伙伴在 GYM NETWORK 中保持活跃，您就可以赚取佣金，这实际上相当于一个不错的被动收入流。帮助其他人通过 DeFi 获利，并以此赚取被动收入。',
  //   turnover_pool_monthly: '每月营业额池',
  //   level_pool_daily: '每日水平池',
  //   regional: '区域',
  //   national: '国家的',
  //   international: '国际的',
  //   gold: '金子',
  //   level: '等级',
  //   platin: '铂金的',
  //   black: '黑色的',

  //   strategy: '战略',
  //   vaults: '金库',
  //   tokens: '代币',
  //   gymnet_icon: '健身房图标',
  //   total_gymnet_vaults_rewards: 'GYMNET 金库总奖励',
  //   claim_all: '索赔全部',
  //   all_vaults: '所有的金库',

  //   rewards: '奖励',
  //   claim: '索赔',
  //   vaultCommissions: '金库佣金',
  //   farmingCommissions: '农业委员会',
  //   singlePoolCommissions: '单池佣金',
  //   vaultCommissionsTotal: '金库佣金总额',
  //   totalInvestorsProfit: '投资者总利润',
  //   pendingCommissions: '待定佣金',
  //   commissionsFromVaultInvestors: '来自金库投资者的佣金',
  //   partnerActivity: '合作伙伴活动',
  //   date: '日期',
  //   user: '用户',
  //   amount: '数量',
  //   token: '代币',
  //   tx: '德克萨斯州',
  //   loadMore: '加载更多',
  //   dailyROI: '每日投资回报率',
  //   hourlyROI: '每小时投资回报率',
  //   totalLiquidity: '总流动性',
  //   totalTokensLocked: '锁定的总代币',
  //   viewContract: '查看合同',
  //   seePairInfo: '查看配对信息',
  //   myStake: '我的赌注',
  //   myStakeText: '在这里您可以存入您的 GYMNET 代币以获得更多奖励',
  //   addLiquidityStake: '增加流动性和权益',
  //   gymnetEarned: 'Gymnet赚了',
  //   claimStake: '索赔和赌注',
  //   addLiquidutyStake: '添加流动性和赌注',
  //   gymnetAndBnb: 'gymnet 和 bnb',
  //   gymnetAndBusd: 'gymnet 和 busd',
  //   gymnet: '体操网',
  //   bnb: 'bnb',
  //   withdraw: '提取',
  //   balanceNum: '余额：ß{n}',
  //   claim_and_farm: '索赔和农场',
  //   compound_your_gymnet: '收取你的 GYMNET',
  //   claimAndFarm: '索赔和农场',
  //   your_total_deposit: '您的总存款',
  //   total_pending_rewards: '总待定奖励',
  //   total_own_claimed: '总共拥有的索赔',
  //   active_holdings: '主动持股',
  //   archived_holdings: '存档资产',
  //   with_locking_period: '有锁定周期',
  //   without_locking_period: '无锁定周期',
  //   deposit_amount: '存款金额',
  //   pending_rewards: '待定奖励',
  //   you_dont_receive_pending_rewards_for_deposit_without_locking_period: '没有锁定期的存款，您不会收到待定奖励',
  //   lpTokensWillBeAutomaticallyStakedOnTheFaringContract: 'LP 代币将自动质押在票价合约上。',
  //   depositFeeForBuyAndBurn: '购买和销毁的 4% 存款费',
  //   unlock: '不锁定',
  //   halfOfYourGymNetTokensWillBeUsed: '您一半的 GYMNET 代币将用于购买 BNB，然后汇集并在质押联系人上质押。',
  //   halfOfYourBnbTokensWillBeUsed: '您一半的 BNB 代币将用于购买 GYMNET，然后汇集并在质押联系人上质押。',
  //   removeLiquidity: '去除流动性',
  //   pooled: '汇集',
  //   unstake: '取消抵押',
  //   lpTokensWillBeInYourWallet: 'LP 代币将在您的钱包中。要获得 BNB 和 GYMNET 代币，请在完成此操作后单击 移除流动性 按钮',
  //   dailyProfit: '每日利润',
  //   withdraw_and_claim: '撤回和索赔',
  //   pending_GYMNET_reward: '等待 GYMNET 奖励',
  //   LP_tokens_will_be_in_your_wallet: 'LP 代币将在您的钱包中。要获得 BNB 和 GYMNET 代币，请在完成此操作后单击 移除流动性 按钮',
  //   claim_and_deposit_to_sp: '索取并存入单池',
  //   claim_and_deposit: '索赔和存款',
  //   deposit_with_locking_period: '锁定期存款',
  //   claimAndDeposit: '索赔和存款',
  //   depositWithLockingPeriod: '锁定期存款',
  //   confirmLockingPeriod: '确认锁定期',
  //   total_gymnet_locked_in_pool: '总 GYMNET 锁定在池中',
  //   total_claimed: '索赔总额',
  //   reward_per_block: '每块奖励',
  //   start_date: '开始日期',
  //   end_date: '结束日期',
  //   launch_of: '推出',
  //   locked: '锁定',
  //   months: '几个月',
  //   nothing_to_show: '无内容',
  //   you_will_receive_commissions_text: '您将从您的下线获得佣金，并将根据排名条件获得资格',
  //   deposit_fee_for_burn: '烧伤押金',
  //   no_data_found: '无数据',
  //   disconnect_wallet: '断开钱包',
  //   confirm_trans: '确认交易',
  //   confirm: '请确认弹出的交易。',
  //   okay: '好的',
  //   waiting_trans: '等待交易确认...',
  //   wait: '请稍等',
  //   confirmed: '交易确认！',

  //   protection_tools: '保护工具',
  //   price_stabilizer: '价格稳定器',
  //   stabilizer_desc: '来自金库10% 的利润用于回购和销毁计划。',

  //   affiliate_system_title: 'GYM网络会员系统',
  //   affiliate_system_info: '通过 GYM Network 的会员系统，您可以建立自己的加密推荐业务和长期被动收入。',
  //   affiliate_desc: '今天成为 GYM Network 社区的一员，并创造你自己的财务自由。',


  //   affiliate_system: '附属系统',

  //   privacy_policy: '隐私政策',

  //   trans_success: '交易成功确认！',
  //   unlock_and_stake: '解除锁定和质押',
  //   deposit_to_sp: '存入单池',
  //   failed: '交易失败',
  //   unlock_staking: '解锁质押',
  //   no_deposit_fee_for_burn: '烧毁不收取押金',
  //   no_apy: '没有收益率',
  //   unlocked: '解锁',
  //   terms_conditions: '条款和细则',
  //   enter_your_email: '输入你的电子邮箱',
  //   verify_email: '验证邮件',
  //   heading: '标题',
  //   your_sponsor_id: '您的赞助商 ID',
  //   terms_condition_accept_info: '接受T&C后，以后将无法更改，将自动执行。',
  //   accept_terms_conditions: '接受条款和条件',
  //   email: '电子邮件',
  //   confirm_your_email: '确认您的电子邮件',
  //   create_account: '创建账户',
  //   email_verification: '电子邮件验证码已发送至',
  //   change_email: '更改电子邮件',
  //   resend_code: '重新发送代码',
  //   turnovers: '营业额',
  //   qualified_level_vault: '符合资质水平的金库',
  //   unlimited_depth_vault: '无限深度金库',
  //   qualified_level_farm: '合格的农场',
  //   unlimited_depth_farm: '无限深度农场',
  //   qualified_depth_single_pool: '合格的深度单池',
  //   unlimited_depth_single_pool: '无限深度单池',
  //   deposit_partners_list: '直接合作伙伴名单',
  //   own_vault_deposit: '自己的金库存款',
  //   level_rank: '等级/等级',
  //   total_deposit_vault: '总存款金库',
  //   total_liquidity_mining: '总流动性挖矿',
  //   total_single_pool: '总单池',
  //   total_partners: '总合作伙伴',
  //   total_pool_rewards: '总池奖励',
  //   total_participants: '参与者总数',
  //   unclaimed_gymnet_rewards: '无人认领的 GYMNET 奖励',
  //   level_pool: '水平池',
  //   vaults_contribution: '金库贡献',
  //   single_contribution: '单一贡献',
  //   farming_contribution: '耕种贡献',
  //   current_pending_rewards: '当前待定奖励',
  //   participants: '参与者',
  //   unclaimed_rewards: '无人认领的奖励',
  //   type: '类型',
  //   txId: '区块链交易哈希',
  //   amount_before: '之前的金额',
  //   amount_after: '之后的金额',
  //   next_distribution: '下一次分发',
  //   ROI_at_current_stake: '目前的投资回报率',
  //   received_gGymnet: '收到 GYMNET',
  //   about_voting_rights: '关于投票权',
  //   you_successfully_verified_your_email: '您成功验证了您的电子邮件',
  //   to_dashboard: '到仪表板',
  //   you_will_receive_your_tokens_text: '您将收到BNB包裹中的代币，请将 WBNB 导入您的钱包以查看您的资金。',
  //   you_will_receive_your_tokens_text_BUSD: '您将收到您的 BUSD 代币，请将 BUSD 导入您的钱包以查看您的资金。',
  //   share_of_NFT_pool: 'NFT池派得的份额',
  //   partner_area: '合作伙伴区',
  //   rockstar_rank_text: '摇滚明星是一个额外的资格获取选项，它允许每个人以更简单的方式获得三个不同等级的资格。 ',
  //   rockstar_ranks: '摇滚明星排名',
  //   to_reach_rank_you_need: '要达到等级 {level} ({name})，您需要：',
  //   all_ranks: '所有等级',
  //   reach_levels_much_easier: '达到 10、23、24 级要容易得多！',
  //   reach_levels_much_easier_text: '你现在可以支付 4% 的购买和销毁费用，并在新的条件下达到未来的水平。优惠在确认 T&C 确认后 30 天内有效。',
  //   rockstar_10_rank: '摇滚明星 10 级',
  //   rockstar_10_rank_text: '您在所有存款中只需要 7500 美元而不是 22000 美元。此外，您将需要较小的存款才能获得 9 级。没有合格的合作伙伴要求。',
  //   single_pool_deposit: '单池存款',
  //   vault_deposit: '金库存款',
  //   farming_deposit: '耕种存款',
  //   next: '下一个',
  //   sponsor_id: '赞助商ID',
  //   back: '后退',
  //   ggymnet_amt: 'gGymnet 金额',
  //   skip_guide: '跳过指南',
  //   total_amount: '总金额',
  //   rockstar10_23_24_ranks: 'Rockstar 10， 23， 24 排名',
  //   rockstar_24_rank: '摇滚明星 24 级',
  //   rockstar_24_rank_text: '您在所有存款中只需要 100000 美元而不是 135000 美元。没有合格的合作伙伴要求。',
  //   rockstar_23_rank: '摇滚明星 23 级',
  //   rockstar_23_rank_text: '您在所有存款中只需要 90000 美元而不是 120000 美元。此外，21、22 等级您将需要较小的存款。没有合格的合作伙伴要求。',
  //   swap: '交换',
  //   member: '成员',
  //   buy: '买',


  //   newsletter: '通讯',
  //   documentation: '文件',
  //   smart_contract: '智能合约',
  //   community: '社区',

  //   help: '帮助',
  //   certik: '经 CERTIK 审核！',


  // // ............................



}
